### ISSUE TITLE
Deprecated: array_key_exists() in PHP 7.4

### ISSUE THREAD

**Issue by OlMon** [ndunand/moodle-mod_choicegroup#147]
Greetings,

I am not sure if this a 3.10 Bug, but now I see a deprecated notification inside the groupchoice.

 Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /app/moodle/mod/choicegroup/renderer.php on line 112

Did not find any issue with this problem, if I missed it I am sry.

Cheers and thanks for the great work!

Cheers,
Marco

**Comment by ndunand** [comment]
Thanks @OlMon for reporting this,

As per the PHP documentation at https://www.php.net/manual/en/function.array-key-exists.php , 

> For backward compatibility reasons, array_key_exists() will also return true if key is a property defined within an object given as array. This behaviour is deprecated as of PHP 7.4.0, and removed as of PHP 8.0.0.

This is deprecated since PHP 7.4, so this is probably why you are seeing this message.

Note for me: offending line is https://github.com/ndunand/moodle-mod_choicegroup/blob/master/renderer.php#L112

I will fix this in the next release, hopefully this summer. In the meantime this won't be any issue on your end unless you start using PHP 8.0.

**Comment by michael-milette** [comment]
Thanks @ndunand !

I see the issue has been fixed in the version here on GitHub. Much better! 👍 

Michael Milette

**Comment by ndunand** [comment]
Indeed @michael-milette this was fixed by 1240d8bd0dc60d975d75c07c1779494d4cc3de23
