### ISSUE TITLE
In Moodle 4.0, the description is shown in the activity view, hence displaying it twice.

### ISSUE THREAD

**Issue by lucaboesch** [ndunand/moodle-mod_choicegroup#171]
When you have a choicegroup activity and the description filled and the "Display description on course page" checked, the description is shown twice in the UI where participants go to perform their choice.
<img width="1261" alt="grafik" src="https://user-images.githubusercontent.com/377279/185622911-292702d9-de37-44f1-a605-6955477c95f4.png">

**Comment by ndunand** [comment]
Hi @lucaboesch sorry I didn't look into this earlier. Indeed this is a problem but since we're not on 4.x yet I haven't figured out a way to do this cleanly on both 3.11 and 4.x. If I remove this line https://github.com/ndunand/moodle-mod_choicegroup/blob/master/view.php#L173 in it works as expected in 4.0 but there is no title anymore in 3.11

How do you deal with this in your other plugins ?

**Comment by lucaboesch** [comment]
Oh, @ndunand it is not that.
That (in the screen grab) "Workshopwahl" twice is perfectly fine.
It's the "Wähle hier den Workshop (…) zu den einzelnen Workshops" that is the description.
(I should have somehow highlighted it.)

Best,
Luca

**Comment by lucaboesch** [comment]
Dear @ndunand and @NicoAlexH 
Seems here https://github.com/elearningsoftware/moodle-mod_journal/issues/86 was the same issue.

Have a look if that solution suits you, too.
