### ISSUE TITLE
Shows my first activity answer to every activities in this list

### ISSUE THREAD

**Issue by simpasami** [ndunand/moodle-mod_choicegroup#176]
![2022-11-02 15_53_58-Group choices](https://user-images.githubusercontent.com/117338882/199658297-d90256ff-77af-458c-8c42-8c7ebb576454.png)

**Comment by mhughes2k** [comment]
I can confirm this issue on under Moodle 3.11.11, plugin version 2021083100

**Comment by simpasami** [comment]
our is Moodle 3.9.18, plugin version is 2021052407

**Comment by NicoAlexH** [comment]
Hello @simpasami, @mhughes2k, 

Thanks for reporting !
I am afraid this behavior occurs by design, the plugin was conceived in a way that does not store a user's answer to a specific choicegroup activity ; we can only determine this user's groups membership. 
Therefore if there are multiple choicegroup activities in a course, the "answer" column will always be filled with every group the user belongs to, not the answer they have selected in the listed activities. 

It would require quite a bit of work to change this behavior and we cannot afford it at the moment, but if you feel like implementing this feature, we would be happy to review and integrate it ! 

Have a nice day, 
Nicolas
