### ISSUE TITLE
Possibility to register even though the registration is already closed

### ISSUE THREAD

**Issue by Atlasfreak** [ndunand/moodle-mod_choicegroup#225]
If you have multiple group selections (doesn't matter if they are in the same course or not) and one is closed while the other one is open, you are able to register to a group in the closed one.
This works by sending the request through the open selection and providing the id of a group within the closed one. It is even possible to do this across courses.

**Comment by ndunand** [comment]
As per #226 this is probably by design for the same reasons. Feel free to elaborate if I have misunderstood the issue. On the other hand, if it was possible to forge requests by providing an arbitrary group ID (e.g. for a group that is not an option for the choicegroup activity), this would obviously be an issue.
